# Copyright (C) 2016 Sahil Sareen (ssareen [AT] gnome [DOT] org)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version. See http://www.gnu.org/copyleft/gpl.html the full text of the
# license.

# Map of cities whose state couldn't be determined by geopy

unmatched_cities = {}


unmatched_cities["Alipurduar"] = "West Bengal"
unmatched_cities["Anekal Bangaluru"] = "Karnataka"
unmatched_cities["Bahalgarh"] = "Haryana"
unmatched_cities["Bardes"] = "Goa"
unmatched_cities["Betul Bazar"] = "Madhya Pradesh"
unmatched_cities["Bhramapur"] = "Odisha"
unmatched_cities["Bokaro Steel City"] = "Jharkhand"
unmatched_cities["Bombaim"] = "Maharashtra"
unmatched_cities["Corbet National Park Naini Tal"] = "Uttarakhand"
unmatched_cities["Daskoi"] = "Gujarat"
unmatched_cities["Dehra Dun Rural"] = "Uttarakhand"
unmatched_cities["Doom Dooma"] = "Assam"
unmatched_cities["Farukhabad"] = "Uttar Pradesh"
unmatched_cities["Fort Kshetra"] = "Karnataka"
unmatched_cities["Fortksherta"] = "Gujarat"
unmatched_cities["Gobindgarh Industrial Area"] = "Punjab"
unmatched_cities["Hooghli"]="West Bengal"
unmatched_cities["Jagadishpur Industrial Area"] = "Uttar Pradesh"
unmatched_cities["Jakhal Mandi"] = "Haryana"
unmatched_cities["Jetpur Navagadh"] = "Gujarat"
unmatched_cities["JhumriTilaiya"] = "Jharkhand"
unmatched_cities["Jogabani"] = "Bihar"
unmatched_cities["KPTCL Kalyan Nagar"] = "Karnataka"
unmatched_cities["Kalol Ahemadabad"] = "Gujarat"
unmatched_cities["Kalyan Dombivali"] = "Maharashtra"
unmatched_cities["Kannur-Padanapalam-Talap"] = "Kerala"
unmatched_cities["Keelakarai"] = "Tamil Nadu"
unmatched_cities["Khudda Lahora"] = "Punjab"
unmatched_cities["Kochas"] = "Bihar"
unmatched_cities["Kondhawa Khurd"] = "Maharashtra"
unmatched_cities["Krishananagar"] = "West Bengal"
unmatched_cities["Lalru"] = "Punjab"
unmatched_cities["Loharpur"] = "Bihar"
unmatched_cities["Majdia"]="West Bengal"
unmatched_cities["Marmagao"] = "Goa"
unmatched_cities["Mehmand"] = "Punjab"
unmatched_cities["Mukundapuram"] = "Kerala"
unmatched_cities["Mulana Bag Area"] = "Delhi"
unmatched_cities["Mylapore Tiruvallike"] = "Tamil Nadu"
unmatched_cities["Nandivaram-Guduvancheri"] = "Tamil Nadu"
unmatched_cities["Nanital"] = "Uttarakhand"
unmatched_cities["Naravarikuppam"] = "Tamil Nadu"
unmatched_cities["Nawashahr"] = "Punjab"
unmatched_cities["Pallakad"] = "Kerala"
unmatched_cities["Panatur"] = "Karnataka"
unmatched_cities["Patna City Outer"] = "Bihar"
unmatched_cities["Pattabhi Puram"] = "Andhra Pradesh"
unmatched_cities["Perambur Purasavakam"] = "Tamil Nadu"
unmatched_cities["Purba Barisha"]="West Bengal"
unmatched_cities["Sanand Industrial Area"] = "Gujarat"
unmatched_cities["Sanaswadi"] = "Maharashtra"
unmatched_cities["Sangareddi"] = "Telangana"
unmatched_cities["Santiniketan"] = "West Bengal"
unmatched_cities["Saraimeera Kannauj"] = "Uttar Pradesh"
unmatched_cities["Sasashti"] = "Goa"
unmatched_cities["Silvassa"] = "Dadra and Nagar Haveli"
unmatched_cities["Sulurpet"] = "Andhra Pradesh"
unmatched_cities["Talappalli"] = "Telangana"
unmatched_cities["Tata Steel City"] = "Jharkhand"
unmatched_cities["Tezpur Rural"] = "Assam"
unmatched_cities["Tiruchirapalli"] = "Tamil Nadu"
unmatched_cities["Tiruvallikeni"] = "Tamil Nadu"
unmatched_cities["Turkayamjal"] = "Andhra Pradesh"
unmatched_cities["Udumalaipettai"] = "Tamil Nadu"
unmatched_cities["Urmar Tanda"] = "Punjab"
unmatched_cities["Vododara"] = "Gujarat"
unmatched_cities["Warangal-Hamamkonda"] = "Telangana"
